### ISSUE TITLE
Poster Diagrams

### ISSUE THREAD

**Issue by Puyomino** [Puyomino/ponggame#11]
We need some UML diagrams for the Pong game poster. These include but are not limited to:
- Sequence diagrams (https://www.lucidchart.com/pages/uml-sequence-diagram)
- Context diagrams
- Data Flow Diagram
- Structure charts
Do some of them, don't have to do all of them because they won't likely fit on the poster lol
Post the diagrams in the replies or into the poster on Canva.

**Comment by huy070206** [comment]
![Sequence drawio](https://github.com/Puyomino/ponggame/assets/170585668/6d950f45-f463-4e61-8020-9510ef0329bb)
i did the sequence diagram first. might need some fixing but u guys can have a look

**Comment by Puyomino** [comment]
I realised that the context diagrams, data flow diagrams and structure charts aren't necessary here, as the program doesn't record or store any data. It only listens for user inputs, then immediately forgets after they have released the button.

If you can find a way to make the other charts, go ahead but I'm not sure if there can be anything there.

**Comment by Puyomino** [comment]
![pong game flowchart drawio](https://github.com/Puyomino/ponggame/assets/142360560/5e52b431-1935-45af-879a-0ca844009ab1)
I made a ball flowchart as that is probably the most complex thing here.
