### ISSUE TITLE
Code Annotation

### ISSUE THREAD

**Issue by Puyomino** [Puyomino/ponggame#15]
The teacher want us to annotate our code like it's English.

We can achieve this by:
- Writing our annotations in the code code comments
- Taking part of the code to a word document and annotating it there
- Print code out and physically write on it

I want to write in code because then everything is in one place but our teacher is *really* against the idea but does allow it.

**Comment by ashrxydud** [comment]
ok

**Comment by Puyomino** [comment]
Do in google slides as it easier

**Comment by Puyomino** [comment]
I did it, however there isn't any submission box for it. So I guess you can check it out on your own. It also uses v1.0 code so any new updates are not shown in the slideshow
